version: "3"

services:
  mysql:
      image: mysql:8.0
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
      ports:
          - 3306:3306
      volumes:
          - ./db/mysql:/var/lib/mysql
  postgresql:
      image: postgres:15-alpine
      environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
      ports:
          - 5432:5432
      volumes:
          - ./db/postgresql:/var/lib/postgresql/data
